[package]
name = "arpwd"
version = "0.1.0"
edition = "2021"

[dependencies]
pbkdf2 = { version = "0.12.2", features = ["simple"] }
sha2 = "0.10.9"
hex = "0.4.3"
rand = "0.9.2"
aes = "0.8.4"
cbc = "0.1.2"
cipher = { version = "0.4.4", features = ["block-padding"] }
